### ISSUE TITLE
[Request]: Explain how to recover from a fast fail

### ISSUE THREAD

**Issue by steveoh** [agrc/api-client#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Fast fail instructs you that the data is bad but that isn't always the case. We can give better instructions of things to geocode successfully. 

https://github.com/agrc/api-client/blob/9a1fe40e48d385c1d0fc6cc99336061a68b6d4bb/src/pages/Geocoding.jsx#L106-L108

### Describe the solution you'd like

The way I see it there are 3 reasons for a fast fail to occur. Starting at the bottom,

1. Your api key is invalid.
2. The fields are mapped incorrectly.
3. The data has 25 initial bad rows.

The solutions are simple

1. Click the api key in the top right to see if you get a thumbs up. Create a new key if you fouled this up. **We should read the api response and highlight this option**.
2. Check your field mapping. Does the sample data look correct?
3. Remove or reorder the first 25 rows of your data.

Add these items to the page to help the task get back on track.

**Comment by stdavis** [comment]
A fourth reason may be that the API is down...

**Comment by steveoh** [comment]
Yup, we only link out to the status page when the error page is shown. This would be another good spot.
