### ISSUE TITLE
Implement Sentry

### ISSUE THREAD

**Issue by stdavis** [agrc/api-client#104]
I've gone down a huge rabbit hole trying to implement Sentry. It would be good for both of us to take a look at it together. I've push a `wip` commit of where I got to. My main issue is trying to call `init` from the preload script. I've read that it need to be called in `main`, `renderer`, and `preload`. I feel like I'm one webpack config from getting it working.

I did run `node sentry-symbols.js` to upload the electron symbols.

Some helpful links:

https://docs.sentry.io/platforms/javascript/guides/electron/

https://github.com/getsentry/sentry-electron/issues/366

[This comment](https://github.com/getsentry/sentry-electron/issues/366#issuecomment-963443825) makes me think that we should just wait until [v3 final of @sentry/electron](https://github.com/getsentry/sentry-electron/releases) is released.

_Originally posted by @stdavis in https://github.com/agrc/api-client/issues/75#issuecomment-963474327_

**Comment by steveoh** [comment]
closed by #121
