### ISSUE TITLE
[Request]: handle sub-addresses

### ISSUE THREAD

**Issue by gregbunce** [agrc/api-client#107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

addresses containing sub-addresses do not geocode, and return a score of 0. 

### Describe the solution you'd like

geocode the address without the sub-address (aka: remove the sub-address) - or even better, incorporate the sub-address in the geocoding process.

**Comment by steveoh** [comment]
Please provide some examples. If you are talking about apartments/units etc this should work already.

**Comment by gregbunce** [comment]
will do

**Comment by gregbunce** [comment]
this conversation has moved to this bug issue: 
https://github.com/agrc/api-client/issues/108
