### ISSUE TITLE
[Bug]: rows with sub-address in 'street' field returns with geocode score of zero

### ISSUE THREAD

**Issue by gregbunce** [agrc/api-client#108]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### App Version

1.5.2

### Electron Version

16.0.1

### Operating System

Windows

### What happened?

records/rows in my .csv file that contained a sub-address in the street field did not geocode and returned with a score of 0.  it could be b/c the sub-address was prefixed with a pound (#).  Example:

`street, zone`
`81 E 100 N #23, 84535`

![image](https://user-images.githubusercontent.com/16906316/147689007-b70ecc8a-0883-4c6c-a741-f24c85af5362.png)

### Steps To Reproduce

I generated the list of addresses from the open sgid address points using this query:
`select fulladd as street, zipcode as zone from location.address_points limit 50 `

here's the output .csv from that query:
[sample_geocodes.csv](https://github.com/agrc/api-client/files/7790016/sample_geocodes.csv)

**Comment by steveoh** [comment]
Thanks greg! Good find 🔍 

This looks like a difference between regex in python and node. We converted the geocoding toolbox to javascript.

nodejs
![image](https://user-images.githubusercontent.com/325813/147691527-b59a13d9-ce1c-492c-a48a-de2d061e6616.png)

python
![image](https://user-images.githubusercontent.com/325813/147691602-b2df1a3a-4d20-403e-999d-4fae0c276ddc.png)

**Comment by stdavis** [comment]
Thanks for the catch and report, @gregbunce!
