### ISSUE TITLE
Better Download Links

### ISSUE THREAD

**Issue by stdavis** [agrc/api-client#112]
This is not very user-friendly:
![image](https://user-images.githubusercontent.com/1326248/148575891-1260c4b5-f86d-4976-9b55-e9b8a0e4f351.png)

I wonder if there's a way to give users more clear download buttons like "Window" and "macOS" rather than expecting them to know which of these files is the correct one for their OS.

Maybe we could have generic download links on the Readme? The hard part would be updating them with each release. Maybe we could do that via a GitHub action. Or maybe we need a product page on gis.utah.gov that dynamically queries the electron updates endpoint and presents the latest link to the user.

Or maybe we could get rid of the version numbers in the release assets and link to them [like this](https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases#:~:text=To%20link%20directly%20to%20a%20download%20of%20your%20latest%20release%20asset%20that%20was%20manually%20uploaded%2C%20link%20to%20/owner/name/releases/latest/download/asset%2Dname.zip).

**Comment by steveoh** [comment]
I think our website product page solves this.
