### ISSUE TITLE
App Crash Report

### ISSUE THREAD

**Issue by cbutlerp** [agrc/api-client#136]
### What happened?
I just now tried it again. 
It crashed.
It never updated  to new version 1.6. 

### App Version

1.5.7

### Electron Version

17.0.0

### Operating System

macOS Monterey

#### Error message

`Error invoking remote method 'geocode': TypeError: Cannot read properties of undefined (reading 'statusCode')`

#### Stack trace

```st
Error: Error invoking remote method 'geocode': TypeError: Cannot read properties of undefined (reading 'statusCode')
```

**Comment by steveoh** [comment]
Please allow your application to update to 1.6.0 before submitting another issue report.
