### ISSUE TITLE
Add Version Bump To Download Links on gis.utah.gov

### ISSUE THREAD

**Issue by stdavis** [agrc/api-client#137]
It would be nice to have the deploy action automatically make a [commit like this](https://github.com/agrc/gis.utah.gov/pull/2010/files).

**Comment by stdavis** [comment]
This is no longer relevant. gis.utah.gov now has a generic link to the releases page.

**Comment by steveoh** [comment]
The website should be pulling the most recent release assets and falling back to a generic link if that fails.
