### ISSUE TITLE
[Request]: Provide instructions for building from source

### ISSUE THREAD

**Issue by twiclo** [agrc/api-client#188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I run desktop linux and would like to compile this myself but am unfamiliar with this project structure.

### Describe the solution you'd like

Could you update the read me to give instructions on how to build it from source?

**Comment by steveoh** [comment]
It should be 

1. git checkout
2. npm install
3. npm start

Please close the issue if that allows you to build from source.

**Comment by twiclo** [comment]
That does it
