### ISSUE TITLE
Feature: API Single Line Geocoder

### ISSUE THREAD

**Issue by rkelson** [agrc/api-client#213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

This would allow users to take an address they have or received and get the most valid address as UGRC sees it. 

Ex. DABS gets a request for a new license at `955 E Expressway  Spanish Fork`. Dabs then puts that address through the geocoder/validator and it returns `955 E Expressway LN, Spanish Fork, Utah 84660`, the valid address they should record for the new license record.

In the perfect world it would be great if Health, Dept. of Education, etc. would clean up the addresses in the tables they maintain so when we get the table updates we simply geocode valid addresses vs. having to clean all the addresses prior to geocoding everytime.

**Comment by steveoh** [comment]
@rkelson can you describe a little about the solution to your request. What would you expect to do in the app? Like would you expect it to load and ask you if you have a single or multiple then have some inputs like atlas and then what result would you expect to see when you put in a good address or a bad address and press a button?

**Comment by rkelson** [comment]
Something similar to the UGRC API Client that provides a simple single line interface to input an address then return the complete correct address. Maybe a copy button to capture the address returned. I am thinking something focused on address validation/address correction rather than an actual geocoder. Scores and a pick list could be provided with match rates unless there is a match score of >=90. There could be a small inset map that would show the point's geocoded location automatically or there could be a button "Show me on a map" that would open something like Atlas to the geocoded location for validation.

**Comment by steveoh** [comment]
This is the UGRC API Client so I'm a bit confused how it could be similar. Are you suggesting another app or a new feature in the existing app? 

You're interested in a single line entry and address correction and validation. Would you want the ability to apply the rules from to the sweeper projects address methods and the ability to geocode to get scores and coordinates?

**Comment by rkelson** [comment]
New app or new feature. However you want. Maybe just an addition below uploading of a .csv file api where there is a line to input a single line address. I am looking for something for folks well outside our office and the GIS community to take an address they are provided, validate it, and be returned the most correct single line address to use to record a location record.

You could also provide the parsed pieces of the address and XY but what my idea is, is to simply allow users to input some address (ex. `852 East State Street, American Fork`) and be returned the complete and validated address (ex. `852 E State St., American Fork, UT, 84003`)

**Comment by rkelson** [comment]
yes the components of the complete address are in the address point fields

**Comment by stdavis** [comment]
This sounds like a website more than something that someone has to download and install to use. addressverification.ugrc.utah.gov. A simple text input and then a bunch of output associated with the matched address including an inset map.

**Comment by steveoh** [comment]
We should probably move this to darwin

**Comment by stdavis** [comment]
[It's already there](https://github.com/agrc/darwin/discussions/11).
