### ISSUE TITLE
App Crash Report - directions unclear

### ISSUE THREAD

**Issue by tysongibby** [agrc/api-client#229]
### What happened?
LOVING this resource! Thank you!
The formatting the csv file needs is unclear. Please provide a few rows of example data that includes the required header on the "Add your data" page for the client (see attached AGRC_API_Client_AddYourData_Screenshot.png)
![AGRC_API_Client_AddYourData_Screenshot](https://github.com/agrc/api-client/assets/12217620/6c7858c6-22e1-44dc-be56-ac16fbc09190)

Trying to use Windows AGRC API Client. After uploading my csv file with a sample address I get the error 
```
Cannot read properties of undefined (reading 'path')
TypeError: Cannot read properties of undefined (reading 'path')
    at l (file:///C:/Users/tyson/AppData/Local/ugrc-api-client/app-1.6.0/resources/app.asar/.webpack/renderer/main_window/index.js:2:470722)
    at file:///C:/Users/tyson/AppData/Local/ugrc-api-client/app-1.6.0/resources/app.asar/.webpack/renderer/main_window/index.js:2:374614
    at file:///C:/Users/tyson/AppData/Local/ugrc-api-client/app-1.6.0/resources/app.asar/.webpack/renderer/main_window/index.js:2:374832
```

### Steps To Reproduce

Run client
Enter Key
Upload csv file

### App Version

1.6.0

### Electron Version

18.0.4

### Operating System

Windows 11

#### Error message

`Cannot read properties of undefined (reading 'path')`

#### Stack trace

```st
TypeError: Cannot read properties of undefined (reading 'path')
    at l (file:///C:/Users/tyson/AppData/Local/ugrc-api-client/app-1.6.0/resources/app.asar/.webpack/renderer/main_window/index.js:2:470722)
    at file:///C:/Users/tyson/AppData/Local/ugrc-api-client/app-1.6.0/resources/app.asar/.webpack/renderer/main_window/index.js:2:374614
    at file:///C:/Users/tyson/AppData/Local/ugrc-api-client/app-1.6.0/resources/app.asar/.webpack/renderer/main_window/index.js:2:374832
```

**Comment by steveoh** [comment]
Thank you for the issue and I apologize that you're having a hard time with the CSV file.

We've tried to make the CSV file as generic as possible to allow for any variety of schema. I believe all that is required is that you have 3 columns with a header row.

Once you select a CSV the app presents some options to connect to the fields we need. e.g.

![image](https://github.com/agrc/api-client/assets/325813/4a77417d-1887-4793-bcc7-47151cc2c0d0)

What you are showing almost makes it look like the app cannot access the file you are uploading.

**Comment by tysongibby** [comment]
Thanks for such a quick response. That is what I thought at first, too. Not sure they the drag and drop will not work. Uploaded with the "Choose File" (file broswer) and it worked.  Suggestion, maybe provide an example of what the file should like llike on the "Add your data" screen. Something like:
```
address, city, state, zip
3950 Adams Ave, Ogden, UT, 84403
```

**Comment by steveoh** [comment]
Ok, so your issue was with the drag and drop? I'll create a new issue from your suggestion. Thanks!
