### ISSUE TITLE
[Bug]: v1.7.0 built version does not run on intel macs

### ISSUE THREAD

**Issue by stdavis** [agrc/api-client#255]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### App Version

1.7.0

### Electron Version

??

### Operating System

MacOS

### What happened?

![image](https://github.com/agrc/api-client/assets/1326248/15efa983-be27-49d0-8d53-f86a8202b97f)

### Steps To Reproduce

Open the app

**Comment by steveoh** [comment]
The electron version should be 30 something I thought...

**Comment by steveoh** [comment]
Should we pull this version?

**Comment by stdavis** [comment]
Probably. It's hard to say. Do we want to support intel or apple silicon macs? I think that my vote would be to just add a note to the README about intel-based macs and point them at the older version. It appears to me that intel macs don't auto-upgrade to the unsupported version:
<img width="758" alt="image" src="https://github.com/agrc/api-client/assets/1326248/570aaa20-80cf-424e-a841-8695e11ed29d">

**Comment by steveoh** [comment]
I'd like to figure out what caused changes to the support matrix. I wonder if it's the github hosted runners or new versions?

**Comment by stdavis** [comment]
I assume that it was the switch from darwin to arm-based builds?

**Comment by steveoh** [comment]
I didn't change anything in the code to explicitly specify ARM. We are still using the darwin token in the maker.

I think https://github.com/electron/universal is the solution.

**Comment by stdavis** [comment]
This has been resolved.
