### ISSUE TITLE
Release Drafter is suggesting an incorrect version number

### ISSUE THREAD

**Issue by stdavis** [agrc/api-client#49]
https://github.com/agrc/api-client/releases/tag/untagged-5fc3a354463c400c3ed5 should be v1.3.0, no?

**Comment by steveoh** [comment]
No, 1.1.0 is current. 1.2.0 is draft because we merged some feature pull requests. I think 1.3.0 would be skipping a minor.

**Comment by steveoh** [comment]
Yeah, we must have fouled that up and we will need to sync them to start "fresh" yes.
