### ISSUE TITLE
[Request]: Remember Window Position

### ISSUE THREAD

**Issue by stdavis** [agrc/api-client#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

It's a pain to resize and reposition the window each time I restart the app.

### Describe the solution you'd like

It would be super-helpful if this app remembered its window size and position between sessions.

**Comment by steveoh** [comment]
should we use https://github.com/mawie81/electron-window-state and have a second config file or vendorish and combine with our store?

**Comment by stdavis** [comment]
I'm not following with regards to a config file/store, but that package looks like the right fit to me.

**Comment by steveoh** [comment]
That package creates/manages its own config file. We use electron-store for our config file. If we use that package we will have two config files.

**Comment by stdavis** [comment]
Oh, I see. I would let it manage its own config file independent of ours.
