### ISSUE TITLE
[Bug]: Files without a header don't seem to geocode first row

### ISSUE THREAD

**Issue by jacobdadams** [agrc/api-client#97]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### App Version

1.5.1

### Electron Version

16.0.1

### Operating System

Windows

### What happened?

If I provide a csv without a header that has 522 rows and select the proper matching fields, the preview only shows 521 rows and the output only has 521 rows as well, missing the top row.

### Steps To Reproduce

1. Delete the header row from a csv. Note the number of rows and the top row.
2. Geocode, selecting the proper fields.
3. Compare number of rows geocoded and output to input file.

**Comment by steveoh** [comment]
Right now we require a header row. Please make an enhancement request for this.

![image](https://user-images.githubusercontent.com/325813/143966556-e9745be7-5507-4982-9098-65ac707a2058.png)
